// <auto-generated />
using System;
using AdvisorLeads.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdvisorLeads.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("AdvisorLeads.Models.Advisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BcDisclosureCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BcScope")
                        .HasColumnType("TEXT");

                    b.Property<string>("BrokerCheckReportPdfUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("BrokerCheckUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CareerStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CourtRecordDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CourtRecordEnrichedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CourtRecordFlag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourtRecordSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("CourtRecordUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("CrdNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("CrmId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentFirmCrd")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentFirmId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentFirmName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CurrentFirmStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisclosureCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("DisclosureFlags")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DisclosureSeverityScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExclusionReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirmChangeDetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasActiveSanction")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasCivilDisclosure")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasCriminalDisclosure")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasCustomerComplaintDisclosure")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasDisclosures")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("HasFinancialDisclosure")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasRecentFirmChange")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasRegulatoryDisclosure")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasSecEnforcementAction")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasTerminationDisclosure")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IaDisclosureCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IaScope")
                        .HasColumnType("TEXT");

                    b.Property<string>("IapdLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("IapdNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExcluded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsFavorited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsImportedToCrm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsWatched")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastEmploymentCheckDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Licenses")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MaxFineAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MobilityScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("MobilityScoreUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherNames")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Qualifications")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordType")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegAuthorities")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationStatus")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SanctionEnrichedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SanctionType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SecEnforcementEnrichedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecEnforcementUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("Suffix")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalFirmCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZipCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("City");

                    b.HasIndex("CrdNumber")
                        .IsUnique();

                    b.HasIndex("CurrentFirmCrd");

                    b.HasIndex("CurrentFirmId");

                    b.HasIndex("CurrentFirmName");

                    b.HasIndex("DisclosureCount");

                    b.HasIndex("HasDisclosures");

                    b.HasIndex("IsExcluded");

                    b.HasIndex("IsFavorited");

                    b.HasIndex("IsImportedToCrm");

                    b.HasIndex("IsWatched");

                    b.HasIndex("LastName");

                    b.HasIndex("RecordType");

                    b.HasIndex("Source");

                    b.HasIndex("State");

                    b.HasIndex("YearsOfExperience");

                    b.HasIndex("IsExcluded", "IsFavorited");

                    b.HasIndex("IsExcluded", "LastName");

                    b.HasIndex("State", "RecordType", "RegistrationStatus", "LastName");

                    b.ToTable("Advisors", (string)null);
                });

            modelBuilder.Entity("AdvisorLeads.Models.AdvisorCourtRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdvisorCrd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AdvisorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseType")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Court")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("DocketNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FilingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdvisorCrd");

                    b.ToTable("AdvisorCourtRecords", (string)null);
                });

            modelBuilder.Entity("AdvisorLeads.Models.AdvisorList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.ToTable("AdvisorLists", (string)null);
                });

            modelBuilder.Entity("AdvisorLeads.Models.AdvisorListMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<int>("AdvisorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ListId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdvisorId");

                    b.HasIndex("ListId");

                    b.HasIndex("ListId", "AdvisorId")
                        .IsUnique();

                    b.ToTable("AdvisorListMembers", (string)null);
                });

            modelBuilder.Entity("AdvisorLeads.Models.AdvisorRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdvisorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegistrationCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SroName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdvisorId");

                    b.HasIndex("RegistrationType");

                    b.HasIndex("AdvisorId", "RegistrationType", "StateCode", "RegistrationCategory");

                    b.ToTable("AdvisorRegistrations", (string)null);
                });

            modelBuilder.Entity("AdvisorLeads.Models.AlertLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("EntityCrd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAcknowledged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("NewValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlertType");

                    b.HasIndex("DetectedAt");

                    b.HasIndex("EntityCrd");

                    b.HasIndex("IsAcknowledged");

                    b.HasIndex("IsRead");

                    b.HasIndex("EntityCrd", "AlertType", "DetectedAt");

                    b.ToTable("AlertLog", (string)null);
                });

            modelBuilder.Entity("AdvisorLeads.Models.Disclosure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdvisorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resolution")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sanctions")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.HasIndex("AdvisorId");

                    b.ToTable("Disclosures", (string)null);
                });

            modelBuilder.Entity("AdvisorLeads.Models.EdgarSearchResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessionNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cik")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime?>("FilingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilingUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmCrd")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormType")
                        .HasColumnType("TEXT");

                    b.Property<double?>("RelevanceScore")
                        .HasColumnType("REAL");

                    b.Property<string>("SearchQuery")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Snippet")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccessionNumber");

                    b.HasIndex("Category");

                    b.HasIndex("FirmCrd");

                    b.HasIndex("AccessionNumber", "SearchQuery");

                    b.ToTable("EdgarSearchResults", (string)null);
                });

            modelBuilder.Entity("AdvisorLeads.Models.EmploymentChangeEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdvisorCrd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AdvisorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdvisorName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromFirmCrd")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromFirmName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToFirmCrd")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToFirmName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdvisorCrd");

                    b.HasIndex("DetectedAt");

                    b.ToTable("EmploymentChangeEvents", (string)null);
                });

            modelBuilder.Entity("AdvisorLeads.Models.EmploymentHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdvisorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmCrd")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmState")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationCategories")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdvisorId");

                    b.ToTable("EmploymentHistory", (string)null);
                });

            modelBuilder.Entity("AdvisorLeads.Models.FinraSanction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdvisorCrd")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AdvisorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FineAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmCrd")
                        .HasColumnType("TEXT");

                    b.Property<string>("InitiatedBy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("SanctionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SanctionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SuspensionEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SuspensionStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdvisorCrd");

                    b.HasIndex("FirmCrd");

                    b.ToTable("FinraSanctions", (string)null);
                });

            modelBuilder.Entity("AdvisorLeads.Models.Firm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AdvisorCountChange1Yr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdvisoryActivities")
                        .HasColumnType("TEXT");

                    b.Property<string>("AumDescription")
                        .HasColumnType("TEXT");

                    b.Property<bool>("BrokerProtocolMember")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("BrokerProtocolUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessType")
                        .HasColumnType("TEXT");

                    b.Property<string>("CCOName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CFOName")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClientsBankingInstitutions")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientsCharitable")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientsGovernment")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientsHighNetWorth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientsIndividuals")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientsInvestmentCompanies")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientsOther")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientsPensionPlans")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CompensationCommission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool?>("CompensationFeeOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool?>("CompensationHourly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool?>("CompensationPerformanceBased")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("CrdNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<bool?>("CryptoExposure")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("DirectIndexing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EdgarCik")
                        .HasColumnType("TEXT");

                    b.Property<string>("FaxPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("FiscalYearEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FormAdvDeepEnrichedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasActiveSanction")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasCustody")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool?>("HasDiscretionaryAuthority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("HasSecEnforcementAction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvestmentStrategies")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsBrokerDealer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsDuallyRegistered")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExcluded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsInsuranceCompany")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRegisteredWithFinra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRegisteredWithSec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsWatched")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("LatestFilingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LegalName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MailingAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketingArrangements")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MaxFineAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("NumClients")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumberOfAdvisors")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumberOfEmployees")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumberOfOffices")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnershipStructure")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PriorAdvisorCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PriorAdvisorCountDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrivateFundCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("PrivateFundGrossAssets")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationStatus")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RegulatoryAum")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RegulatoryAumNonDiscretionary")
                        .HasColumnType("TEXT");

                    b.Property<string>("SECNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("SECRegion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SanctionEnrichedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SanctionType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SecEnforcementEnrichedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SicCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("SicDescription")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("SoftDollarArrangements")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateOfOrganization")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalAumRelatedPersons")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("WrapFeePrograms")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZipCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrokerProtocolMember");

                    b.HasIndex("City");

                    b.HasIndex("CrdNumber")
                        .IsUnique();

                    b.HasIndex("IsExcluded");

                    b.HasIndex("IsWatched");

                    b.HasIndex("Name");

                    b.HasIndex("RecordType");

                    b.HasIndex("RegulatoryAum");

                    b.HasIndex("IsExcluded", "State", "RecordType");

                    b.HasIndex("State", "RegistrationStatus", "Name");

                    b.ToTable("Firms", (string)null);
                });

            modelBuilder.Entity("AdvisorLeads.Models.FirmAumAlertRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("FirmCrd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ThresholdAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThresholdType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FirmCrd");

                    b.HasIndex("IsActive");

                    b.ToTable("FirmAumAlertRules", (string)null);
                });

            modelBuilder.Entity("AdvisorLeads.Models.FirmAumHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("FirmCrd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("NumClients")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumberOfAdvisors")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumberOfEmployees")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("RegulatoryAum")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RegulatoryAumNonDiscretionary")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalAum")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FirmCrd");

                    b.HasIndex("SnapshotDate");

                    b.HasIndex("FirmCrd", "SnapshotDate")
                        .IsUnique();

                    b.ToTable("FirmAumHistory", (string)null);
                });

            modelBuilder.Entity("AdvisorLeads.Models.FirmFiling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AcceptanceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessionNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cik")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FilingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilingUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmCrd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FormType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryDocument")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccessionNumber")
                        .IsUnique();

                    b.HasIndex("FirmCrd");

                    b.HasIndex("FirmCrd", "FilingDate");

                    b.ToTable("FirmFilings", (string)null);
                });

            modelBuilder.Entity("AdvisorLeads.Models.FirmFilingEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmCrd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReviewed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("NewValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .HasColumnType("TEXT");

                    b.Property<double?>("PercentChange")
                        .HasColumnType("REAL");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventDate");

                    b.HasIndex("EventType");

                    b.HasIndex("FirmCrd");

                    b.HasIndex("Severity");

                    b.HasIndex("FirmCrd", "EventDate");

                    b.ToTable("FirmFilingEvents", (string)null);
                });

            modelBuilder.Entity("AdvisorLeads.Models.FirmOwnership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("EntityType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FilingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmCrd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDirectOwner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("OwnerCrd")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OwnershipPercent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FirmCrd");

                    b.HasIndex("FirmCrd", "FilingDate");

                    b.ToTable("FirmOwnership", (string)null);
                });

            modelBuilder.Entity("AdvisorLeads.Models.FormAdvFiling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AdvisorCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BusinessName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime>("FilingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilingType")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmCrd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("NumClients")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumberOfAdvisors")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumberOfEmployees")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegistrationStatus")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RegulatoryAum")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RegulatoryAumNonDiscretionary")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalAum")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilingDate");

                    b.HasIndex("FirmCrd");

                    b.HasIndex("FirmCrd", "FilingDate");

                    b.ToTable("FormAdvFilings", (string)null);
                });

            modelBuilder.Entity("AdvisorLeads.Models.MarketWatchRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("LicenseContains")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MinYearsExperience")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecordType")
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("MarketWatchRules", (string)null);
                });

            modelBuilder.Entity("AdvisorLeads.Models.Qualification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdvisorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdvisorId");

                    b.ToTable("Qualifications", (string)null);
                });

            modelBuilder.Entity("AdvisorLeads.Models.SecEnforcementAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdvisorCrd")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FileDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmCrd")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("RespondentName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdvisorCrd");

                    b.HasIndex("FirmCrd");

                    b.ToTable("SecEnforcementActions", (string)null);
                });

            modelBuilder.Entity("AdvisorLeads.Models.Advisor", b =>
                {
                    b.HasOne("AdvisorLeads.Models.Firm", null)
                        .WithMany()
                        .HasForeignKey("CurrentFirmId");
                });

            modelBuilder.Entity("AdvisorLeads.Models.AdvisorListMember", b =>
                {
                    b.HasOne("AdvisorLeads.Models.Advisor", "Advisor")
                        .WithMany()
                        .HasForeignKey("AdvisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdvisorLeads.Models.AdvisorList", null)
                        .WithMany()
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advisor");
                });

            modelBuilder.Entity("AdvisorLeads.Models.AdvisorRegistration", b =>
                {
                    b.HasOne("AdvisorLeads.Models.Advisor", null)
                        .WithMany("Registrations")
                        .HasForeignKey("AdvisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdvisorLeads.Models.Disclosure", b =>
                {
                    b.HasOne("AdvisorLeads.Models.Advisor", null)
                        .WithMany("Disclosures")
                        .HasForeignKey("AdvisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdvisorLeads.Models.EmploymentHistory", b =>
                {
                    b.HasOne("AdvisorLeads.Models.Advisor", null)
                        .WithMany("EmploymentHistory")
                        .HasForeignKey("AdvisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdvisorLeads.Models.Qualification", b =>
                {
                    b.HasOne("AdvisorLeads.Models.Advisor", null)
                        .WithMany("QualificationList")
                        .HasForeignKey("AdvisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdvisorLeads.Models.Advisor", b =>
                {
                    b.Navigation("Disclosures");

                    b.Navigation("EmploymentHistory");

                    b.Navigation("QualificationList");

                    b.Navigation("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
